workspace:
  base: /go
  path: src/github.com/minhdanh/digitalocean_exporter

pipeline:
  build:
    image: golang:alpine
    pull: true
    commands:
      - apk add -U git make gcc libc-dev
      - make fmt
      - make vet
      - make lint
      - make test
      - make build
    when:
      event: [ push, tag, pull_request ]

  docker:
    image: plugins/docker
    repo: minhdanh/digitalocean_exporter
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_TAG}
    when:
      event: tag
